version: '3'

services:
  assassin:
    build: .
    ports:
      - 8000:8000
    links:
      - chromedp
      - mariadb
    volumes:
      - ./web/:/web/
      - ./dict/:/dict/
  
  chromedp:
    image: knqz/chrome-headless
    ports:
      - 9222:9222
  
  mariadb:
    image: mariadb
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=assassingo
      - MYSQL_USER=ag
      - MYSQL_PASSWORD=agpasswd
      - MYSQL_DATABASE=ag